"""add funcionario model

Revision ID: 0311a3e2508f
Revises: a9bed51a5237
Create Date: 2025-05-21 10:36:17.722400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0311a3e2508f'
down_revision: Union[str, None] = 'a9bed51a5237'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('curso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_curso_id'), 'curso', ['id'], unique=False)
    op.create_table('equipamento',
    sa.Column('codigo', sa.String(length=8), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=True),
    sa.Column('modelo', sa.String(length=100), nullable=True),
    sa.Column('marca', sa.String(length=100), nullable=True),
    sa.Column('cor', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('codigo')
    )
    op.create_index(op.f('ix_equipamento_codigo'), 'equipamento', ['codigo'], unique=False)
    op.create_table('defeito',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=250), nullable=True),
    sa.Column('equipamento_codigo', sa.String(length=8), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['equipamento_codigo'], ['equipamento.codigo'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_defeito_id'), 'defeito', ['id'], unique=False)
    op.create_table('funcionario',
    sa.Column('cpf', sa.String(length=11), nullable=False),
    sa.Column('codigo_cartao', sa.String(length=10), nullable=True),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('curso_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['curso_id'], ['curso.id'], ),
    sa.PrimaryKeyConstraint('cpf')
    )
    op.create_index(op.f('ix_funcionario_cpf'), 'funcionario', ['cpf'], unique=False)
    op.create_table('uso_equipamento',
    sa.Column('protocolo', sa.Integer(), nullable=False),
    sa.Column('equipamento_codigo', sa.String(length=8), nullable=False),
    sa.Column('funcionario_cpf', sa.String(length=11), nullable=False),
    sa.Column('data_aluguel', sa.DateTime(), nullable=False),
    sa.Column('data_devolucao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['equipamento_codigo'], ['equipamento.codigo'], ),
    sa.ForeignKeyConstraint(['funcionario_cpf'], ['funcionario.cpf'], ),
    sa.PrimaryKeyConstraint('protocolo')
    )
    op.create_index(op.f('ix_uso_equipamento_protocolo'), 'uso_equipamento', ['protocolo'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_uso_equipamento_protocolo'), table_name='uso_equipamento')
    op.drop_table('uso_equipamento')
    op.drop_index(op.f('ix_funcionario_cpf'), table_name='funcionario')
    op.drop_table('funcionario')
    op.drop_index(op.f('ix_defeito_id'), table_name='defeito')
    op.drop_table('defeito')
    op.drop_index(op.f('ix_equipamento_codigo'), table_name='equipamento')
    op.drop_table('equipamento')
    op.drop_index(op.f('ix_curso_id'), table_name='curso')
    op.drop_table('curso')
    # ### end Alembic commands ###
