"""insert_cursos

Revision ID: 2a39b4318a28
Revises: 
Create Date: 2025-05-25 16:50:26.761759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a39b4318a28'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('curso',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('nome', sa.String(length=150), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_curso_id'), 'curso', ['id'], unique=False)
    
    op.bulk_insert(
        sa.table('curso',
            sa.column('nome', sa.String)
        ),
        [
            {'nome': 'Engenharia da Computação'},
            {'nome': 'Engenharia Hídrica'},
            {'nome': 'Engenharia Química'},
            {'nome': 'Engenharia de Controle e Automação'}
        ]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_curso_id'), table_name='curso')
    op.drop_table('curso')
    # ### end Alembic commands ###
