"""insert_cursos

Revision ID: 2a39b4318a28
Revises: 
Create Date: 2025-05-25 16:50:26.761759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a39b4318a28'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        INSERT INTO curso (nome) VALUES
        ('Engenharia da Computação'),
        ('Engenharia Hídrica'),
        ('Engenharia Química'),
        ('Engenharia de Controle e Automação');
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
