"""alter_status_uso_equipamento_to_enum

Revision ID: 9adfc7822347
Revises: 7a23633d95a4
Create Date: 2025-06-01 00:51:11.449633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9adfc7822347'
down_revision: Union[str, None] = '7a23633d95a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uso_equipamento', sa.Column('status', sa.Enum('ALOCADO', 'DEVOLVIDO', 'EM_USO', name='statususoequipamento'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('uso_equipamento', 'status')
    # ### end Alembic commands ###
