"""add column profession in users

Revision ID: a9bed51a5237
Revises: 74aa58fa159a
Create Date: 2025-05-20 12:23:52.783932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9bed51a5237'
down_revision: Union[str, None] = '74aa58fa159a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profession', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profession')
    # ### end Alembic commands ###
